### ISSUE TITLE
[QUESTION] CA data for certificate_authority_data option

### ISSUE THREAD

**Issue by vishymakthal** [redhat-actions/oc-login#19]
### Question

Hello, I am trying to setup an action that will oc-login with TLS enabled. I am passing in `certificate_authority_data` from a repository secret, which contains the certificate data from the `tls.crt` field from `openshift-service-ca/signing-key` secret from the cluster. 

Running oc-login with the parameters I pass to the action works fine, however I'm always met with `error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.` when running from the action. 

Would I need to populate the certificate data with something else?

### Context

Step snippet
```
  - name: Authenticate and set context
    uses: redhat-actions/oc-login@v1
    with:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      certificate_authority_data: ${{ secrets.CA_DATA }}
      namespace: ci-test
```

The secret `CA_DATA` contains the certificate in it's standard format like so:
```
-----BEGIN CERTIFICATE-----
            ***
-----END CERTIFICATE-----
```
