### ISSUE TITLE
oc login difference

### ISSUE THREAD

**Issue by maxandersen** [redhat-actions/oc-login#3]
I just noticed that:

```
oc login --token=<token> --server=<server>
```

sets a namespace in kubeconfig.

but:
```
 - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
```

does not.

Resulting in different behavior - and in case of openshift sandbox it means oc login works and I can deploy, but oc login with github action I end up in the wrong place.

Workaround is to set namespace explicitly but I would expect the two would/should behave the same ?
